[package]
name = "ExpDel"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
gag = "1.0.0"
walkdir = "2.5.0"
chrono = "0.4"
itertools = "0.14.0"
tempfile = "3.20.0"
rand = "0.9.2"
filetime = "0.2.25"